// TurboQuant paper-faithful quantization types for ggml.
//
// Adds two block quantization types that implement the full two-stage
// algorithm from Zandieh et al., "TurboQuant: Online Vector Quantization
// with Near-optimal Distortion Rate" (arXiv 2504.19874, ICLR 2026):
//
//   GGML_TYPE_TQ4P_D128 — head_dim 128 (Llama 3.x, Qwen 2.5, Qwen 3)
//   GGML_TYPE_TQ4P_D256 — head_dim 256 (Qwen 3.5 gated attention)
//
// Stage 1: Haar random orthogonal rotation Π + per-coordinate 3-bit
//          Lloyd-Max scalar quantization.
// Stage 2: Gaussian random projection S of residual, store 1 sign bit
//          per coordinate. Unbiased inner-product estimator with
//          √(π/2)/d correction factor.
//
// This is NOT the existing TQ3_0 / TQ3_1S / TQ3_4S path in this fork.
// Those use a signed Walsh-Hadamard rotation with no QJL stage.
//
// Byte layouts (see BYTE_LAYOUT.md for detail):
//
//   TQ4P_D128: 68 B per 128 elements (4.25 bpw)
//   TQ4P_D256: 132 B per 256 elements (~4.13 bpw)
//
// Constants Π, S, and Lloyd-Max centroids are generated by
// patches/stage2-qjl/python/generate_constants.py. Per-layer Π_i and S_i
// are keyed by layer index (seeds: Π_i=42+i, S_i=43+i), matching
// turboquant.py::TurboQuantProd(seed=42+layer_idx). 32 layers supported.
// The layer index is stored in each block header as a single byte.

#pragma once

#include <stdint.h>
#include <stddef.h>

#ifdef __cplusplus
extern "C" {
#endif

// ----- Block sizes -----

#define QK_TQ4P_D128 128
#define QK_TQ4P_D256 256

// ----- Block structs -----
//
// When integrating into the fork, replace `uint16_t` with `ggml_half` /
// `ggml_fp16_t` from ggml-common.h. The bit layout is identical — ggml_half
// is a typedef of uint16_t.

#pragma pack(push, 1)

typedef struct {
    uint16_t orig_norm;       // fp16; ‖x‖ before unit-normalization
    uint16_t res_d;           // fp16; ‖residual‖ in original space
    uint8_t  layer_idx;       // layer index [0, 31]; selects per-layer Π and S
    uint8_t  qs[48];          // 128 × 3-bit Lloyd-Max indices (bitplane packed)
    uint8_t  qjl_signs[16];   // 128 × 1-bit QJL signs (bit set = negative)
} block_tq4p_d128;

_Static_assert(sizeof(block_tq4p_d128) == 69, "block_tq4p_d128 size");

typedef struct {
    uint16_t orig_norm;
    uint16_t res_d;
    uint8_t  layer_idx;       // layer index [0, 31]; selects per-layer Π and S
    uint8_t  qs[96];
    uint8_t  qjl_signs[32];
} block_tq4p_d256;

_Static_assert(sizeof(block_tq4p_d256) == 133, "block_tq4p_d256 size");

#pragma pack(pop)

// ----- Quantize / dequantize -----

// quantize_row_*: in-place-style conversion of `k` fp32 elements into
// `k / QK_*` packed blocks. `k` must be a multiple of QK_*.
// `layer_idx` selects the per-layer Π and S matrices (0..31).
void ggml_quantize_row_tq4p_d128(const float * x, block_tq4p_d128 * y, int64_t k, uint8_t layer_idx);
void ggml_quantize_row_tq4p_d256(const float * x, block_tq4p_d256 * y, int64_t k, uint8_t layer_idx);

// dequantize_row_*: reconstruct fp32 from packed blocks. QJL stage is not
// used for reconstruction (paper: Stage 2 only contributes to inner-product
// estimation). layer_idx is read from each block's header.
void ggml_dequantize_row_tq4p_d128(const block_tq4p_d128 * x, float * y, int64_t k);
void ggml_dequantize_row_tq4p_d256(const block_tq4p_d256 * x, float * y, int64_t k);

// ----- Inner-product estimator -----
//
// Two-step API, designed so the CUDA follow-up can cache Sq across all K
// positions for a given query:
//
//   ggml_tqp_prepare_query_*(q, Sq): once per query, computes Sq = S · q.
//     q:  d fp32 values, unrotated
//     Sq: d fp32 values, caller-allocated
//
//   ggml_tqp_vec_dot_block_*(q, Sq, blk): per (query, K block) pair.
//     Returns the estimated inner product ⟨q, x⟩.
//
// The CPU reference recomputes Sq for every vec_dot call; callers doing a
// full attention pass should amortize via prepare_query.

void  ggml_tqp_prepare_query_d128(const float * q, float * Sq, uint8_t layer_idx);
void  ggml_tqp_prepare_query_d256(const float * q, float * Sq, uint8_t layer_idx);

float ggml_tqp_vec_dot_block_d128(const float * q, const float * Sq,
                                  const block_tq4p_d128 * blk);
float ggml_tqp_vec_dot_block_d256(const float * q, const float * Sq,
                                  const block_tq4p_d256 * blk);

// ----- ggml integration glue -----
//
// Thin wrappers matching ggml's vec_dot signature. The fork's dispatch table
// in ggml-cpu/ggml-cpu.c registers these for the new types.
//
// Signature matches ggml_vec_dot_t in ggml-cpu.h:
//   n  = number of elements
//   s  = output scalar (1 float)
//   bs = stride of s in bytes (usually sizeof(float))
//   vx = quantized K-side pointer (tq4p_d* blocks) — first ptr, per ggml convention
//   bx = stride of vx
//   vy = converted query (fp32 for our `vec_dot_type = GGML_TYPE_F32`)
//   by = stride of vy
//   nrc = number of rows to compute (batch; reference impl supports nrc=1)

void ggml_vec_dot_tq4p_d128_f32(int n, float * s, size_t bs,
                                 const void * vx, size_t bx,
                                 const void * vy, size_t by, int nrc);
void ggml_vec_dot_tq4p_d256_f32(int n, float * s, size_t bs,
                                 const void * vx, size_t bx,
                                 const void * vy, size_t by, int nrc);

// ----- Q8_K-compatible query block -----
//
// Matches the upstream ggml block_q8_K layout (ggml-common.h).
// Used as the query-side type when vec_dot_type = GGML_TYPE_Q8_K.
// The fork's quantize_row_q8_K produces these; we only dequantize here.

#define QK_Q8K 256

#pragma pack(push, 1)
typedef struct {
    float   d;                   // scale (delta)
    int8_t  qs[QK_Q8K];         // quantized values
    int16_t bsums[QK_Q8K / 16]; // sum of quants in groups of 16 (unused here)
} block_q8k_compat;
#pragma pack(pop)

_Static_assert(sizeof(block_q8k_compat) == 292, "block_q8k_compat size");

// ----- Q8_K query dispatch wrappers -----
//
// Same ggml vec_dot signature as the fp32 wrappers above, but vy points to
// block_q8k_compat blocks instead of fp32 values. The implementation
// dequantizes Q8_K to fp32 one block at a time, then applies the same
// Π rotation + QJL estimator. n must be a multiple of 256 (= lcm(D, QK_Q8K)).
//
// Register as the second dispatch entry per type:
//   .vec_dot      = ggml_vec_dot_tq4p_d128_q8k
//   .vec_dot_type = GGML_TYPE_Q8_K

void ggml_vec_dot_tq4p_d128_q8k(int n, float * s, size_t bs,
                                 const void * vx, size_t bx,
                                 const void * vy, size_t by, int nrc);
void ggml_vec_dot_tq4p_d256_q8k(int n, float * s, size_t bs,
                                 const void * vx, size_t bx,
                                 const void * vy, size_t by, int nrc);

// Maximum number of supported layers for per-layer Π/S matrices.
#define TQP_MAX_LAYERS 32

#ifdef __cplusplus
}
#endif
