// TurboQuant paper-faithful quantization types for ggml.
//
// Adds two block quantization types that implement the full two-stage
// algorithm from Zandieh et al., "TurboQuant: Online Vector Quantization
// with Near-optimal Distortion Rate" (arXiv 2504.19874, ICLR 2026):
//
//   GGML_TYPE_TQ4P_D128 — head_dim 128 (Llama 3.x, Qwen 2.5, Qwen 3)
//   GGML_TYPE_TQ4P_D256 — head_dim 256 (Qwen 3.5 gated attention)
//
// Stage 1: Haar random orthogonal rotation Π + per-coordinate 3-bit
//          Lloyd-Max scalar quantization.
// Stage 2: Gaussian random projection S of residual, store 1 sign bit
//          per coordinate. Unbiased inner-product estimator with
//          √(π/2)/d correction factor.
//
// This is NOT the existing TQ3_0 / TQ3_1S / TQ3_4S path in this fork.
// Those use a signed Walsh-Hadamard rotation with no QJL stage.
//
// Byte layouts (see BYTE_LAYOUT.md for detail):
//
//   TQ4P_D128: 68 B per 128 elements (4.25 bpw)
//   TQ4P_D256: 132 B per 256 elements (~4.13 bpw)
//
// Constants Π, S, and Lloyd-Max centroids are generated by
// patches/stage2-qjl/python/generate_constants.py from seeds matching
// turboquant.py (Π: seed=42, S: seed=43). They are compile-time constants,
// shared across all layers. Per-layer variation is a documented follow-up.

#pragma once

#include <stdint.h>
#include <stddef.h>

#ifdef __cplusplus
extern "C" {
#endif

// ----- Block sizes -----

#define QK_TQ4P_D128 128
#define QK_TQ4P_D256 256

// ----- Block structs -----
//
// When integrating into the fork, replace `uint16_t` with `ggml_half` /
// `ggml_fp16_t` from ggml-common.h. The bit layout is identical — ggml_half
// is a typedef of uint16_t.

typedef struct {
    uint16_t orig_norm;       // fp16; ‖x‖ before unit-normalization
    uint16_t res_d;           // fp16; ‖residual‖ in original space
    uint8_t  qs[48];          // 128 × 3-bit Lloyd-Max indices (bitplane packed)
    uint8_t  qjl_signs[16];   // 128 × 1-bit QJL signs (bit set = negative)
} block_tq4p_d128;

_Static_assert(sizeof(block_tq4p_d128) == 68, "block_tq4p_d128 size");

typedef struct {
    uint16_t orig_norm;
    uint16_t res_d;
    uint8_t  qs[96];
    uint8_t  qjl_signs[32];
} block_tq4p_d256;

_Static_assert(sizeof(block_tq4p_d256) == 132, "block_tq4p_d256 size");

// ----- Quantize / dequantize -----

// quantize_row_*: in-place-style conversion of `k` fp32 elements into
// `k / QK_*` packed blocks. `k` must be a multiple of QK_*.
void ggml_quantize_row_tq4p_d128(const float * x, block_tq4p_d128 * y, int64_t k);
void ggml_quantize_row_tq4p_d256(const float * x, block_tq4p_d256 * y, int64_t k);

// dequantize_row_*: reconstruct fp32 from packed blocks. QJL stage is not
// used for reconstruction (paper: Stage 2 only contributes to inner-product
// estimation).
void ggml_dequantize_row_tq4p_d128(const block_tq4p_d128 * x, float * y, int64_t k);
void ggml_dequantize_row_tq4p_d256(const block_tq4p_d256 * x, float * y, int64_t k);

// ----- Inner-product estimator -----
//
// Two-step API, designed so the CUDA follow-up can cache Sq across all K
// positions for a given query:
//
//   ggml_tqp_prepare_query_*(q, Sq): once per query, computes Sq = S · q.
//     q:  d fp32 values, unrotated
//     Sq: d fp32 values, caller-allocated
//
//   ggml_tqp_vec_dot_block_*(q, Sq, blk): per (query, K block) pair.
//     Returns the estimated inner product ⟨q, x⟩.
//
// The CPU reference recomputes Sq for every vec_dot call; callers doing a
// full attention pass should amortize via prepare_query.

void  ggml_tqp_prepare_query_d128(const float * q, float * Sq);
void  ggml_tqp_prepare_query_d256(const float * q, float * Sq);

float ggml_tqp_vec_dot_block_d128(const float * q, const float * Sq,
                                  const block_tq4p_d128 * blk);
float ggml_tqp_vec_dot_block_d256(const float * q, const float * Sq,
                                  const block_tq4p_d256 * blk);

// ----- ggml integration glue -----
//
// Thin wrappers matching ggml's vec_dot signature. The fork's dispatch table
// in ggml-cpu/ggml-cpu.c registers these for the new types.
//
// Signature matches ggml_vec_dot_t in ggml-cpu.h:
//   n  = number of elements
//   s  = output scalar (1 float)
//   bs = stride of s in bytes (usually sizeof(float))
//   vx = quantized K-side pointer (tq4p_d* blocks) — first ptr, per ggml convention
//   bx = stride of vx
//   vy = converted query (fp32 for our `vec_dot_type = GGML_TYPE_F32`)
//   by = stride of vy
//   nrc = number of rows to compute (batch; reference impl supports nrc=1)

void ggml_vec_dot_tq4p_d128_f32(int n, float * s, size_t bs,
                                 const void * vx, size_t bx,
                                 const void * vy, size_t by, int nrc);
void ggml_vec_dot_tq4p_d256_f32(int n, float * s, size_t bs,
                                 const void * vx, size_t bx,
                                 const void * vy, size_t by, int nrc);

#ifdef __cplusplus
}
#endif
