// TurboQuant(-ish) quantization types for ggml.
//
// Adds two block quantization types derived from Zandieh et al.,
// "TurboQuant: Online Vector Quantization with Near-optimal Distortion
// Rate" (arXiv 2504.19874, ICLR 2026):
//
//   GGML_TYPE_TQ4P_D128 — head_dim 128 (Llama 3.x, Qwen 2.5, Qwen 3)
//   GGML_TYPE_TQ4P_D256 — head_dim 256 (Qwen 3.5 gated attention)
//
// Stage 1: random orthogonal rotation Π + 3-bit per-coordinate Lloyd-Max
//          scalar quantization. Π is user-selectable per block:
//              TQP_ROT_HAAR: paper-exact Haar rotation (dense d×d matrix).
//              TQP_ROT_WHT : Randomized Hadamard Transform (1/√d)·H·diag(σ)
//                            — O(d log d) to apply, d-sized sign vector.
//          Both are orthogonal; the same bound analysis applies. WHT is
//          the default because it's cheaper; Haar is available for
//          paper-faithful comparisons.
// Stage 2: Gaussian random projection S of the residual, 1 sign bit per
//          coordinate. Unbiased inner-product estimator with √(π/2)/d
//          correction factor.
//
// This is NOT the existing TQ3_0 / TQ3_1S / TQ3_4S path in this fork —
// those use a signed Walsh-Hadamard rotation with no QJL stage. This
// type keeps the QJL residual-sign estimator.
//
// Byte layouts (see BYTE_LAYOUT.md for detail):
//
//   TQ4P_D128: 69 B per 128 elements (4.3125 bpw)
//   TQ4P_D256: 133 B per 256 elements (~4.16 bpw)
//
// The `layer_idx` byte packs per-layer index, rotation mode, and an
// explicit-override flag:
//
//   Stored in blocks (bit 6 = 0):
//     stored_byte = (rotation << 7) | (layer_idx & 0x1f)
//
//   Passed to quantize calls (bit 6 = explicit flag):
//     bit 6 = 1: "bit 7 is authoritative" — per-call override.
//     bit 6 = 0: "resolve rotation via runtime defaults":
//                per-thread → per-process env → compile-time (WHT).
//
// Bit 7 = 0 → TQP_ROT_WHT  (uses σ sign vector).
// Bit 7 = 1 → TQP_ROT_HAAR (uses Π rotation matrix).
// Bit 5 reserved (must be 0).
//
// Constants σ, Π, S, and Lloyd-Max centroids are all generated by
// patches/stage2-qjl/python/generate_constants.py. Per-layer σ_i, Π_i
// and S_i are keyed by layer index (seeds: Π_i=σ_i=42+i, S_i=43+i). 32
// layers supported.

#pragma once

#include <stdint.h>
#include <stddef.h>

#ifdef __cplusplus
extern "C" {
#endif

// ----- Block sizes -----

#define QK_TQ4P_D64  64
#define QK_TQ4P_D128 128
#define QK_TQ4P_D256 256

// ----- Rotation modes (packed in the high bit of the layer byte) -----

#define TQP_ROT_WHT  0u   // (1/√d)·H·diag(σ), O(d log d), per-layer σ vector
#define TQP_ROT_HAAR 1u   // dense d×d Haar rotation Π, paper-exact

// Pack / unpack helpers for the `layer_idx` byte.
//
// Block storage layout (bit 6 always 0):
//   stored_byte = (rotation << 7) | (layer & 0x1f)
//
// Quantize-call layout (bit 6 = explicit flag):
//   bit 6 = 1: "bit 7 is authoritative" — per-call explicit override.
//   bit 6 = 0: "resolve rotation via runtime defaults":
//              per-thread > per-process env > compile-time (WHT).
//   The quantize function always clears bit 6 before storing.
//
// TQP_LAYER_BYTE sets bit 6 so callers who specify a rotation get it
// honored as-is, matching pre-runtime-selector behavior.
// TQP_STORED_BYTE does NOT set bit 6 — used only for block storage.
#define TQP_BIT6_EXPLICIT          (1u << 6)
#define TQP_LAYER_BYTE(layer, rot) ((uint8_t)(TQP_BIT6_EXPLICIT | (((uint32_t)(rot) & 1u) << 7) | ((uint32_t)(layer) & 0x1fu)))
#define TQP_STORED_BYTE(layer, rot) ((uint8_t)((((uint32_t)(rot) & 1u) << 7) | ((uint32_t)(layer) & 0x1fu)))
#define TQP_EXTRACT_LAYER(byte)    ((uint8_t)((byte) & 0x1fu))
#define TQP_EXTRACT_ROT(byte)      ((uint8_t)(((byte) >> 7) & 1u))
#define TQP_EXTRACT_EXPLICIT(byte) ((uint8_t)(((byte) >> 6) & 1u))

// ----- Runtime rotation selector -----
//
// Three-tier resolution: per-call explicit > per-thread > per-process > WHT.
//
// tqp_set_default_rotation: sets the process-wide default.
//   rot = TQP_ROT_WHT (0), TQP_ROT_HAAR (1), or 0xff to clear.
//   Also initialized from env var OLLAMA_TQP_ROTATION={wht,haar} at
//   first use (via pthread_once).
//
// tqp_set_thread_rotation / tqp_clear_thread_rotation: per-thread override.
//   Used by ollama's attention module to pre-declare a rotation for a
//   scope of quantize calls.
//
// tqp_resolve_rotation: apply the precedence chain to a layer_byte.
//   If bit 6 = 1 (explicit): return byte with bit 6 cleared.
//   If bit 6 = 0: resolve from thread-local > process default > WHT,
//   write resolved rotation into bit 7, return byte with bit 6 = 0.

void    tqp_set_default_rotation(uint8_t rot);
void    tqp_set_thread_rotation(uint8_t rot);
void    tqp_clear_thread_rotation(void);
uint8_t tqp_resolve_rotation(uint8_t layer_byte);

// ----- Block structs -----
//
// When integrating into the fork, replace `uint16_t` with `ggml_half` /
// `ggml_fp16_t` from ggml-common.h. The bit layout is identical — ggml_half
// is a typedef of uint16_t.

// Block struct: 5 header bytes + D*3/8 qs + D/8 signs = 5 + D/2 total.
// To add a new dim D, define a block struct below with the right array sizes.

#pragma pack(push, 1)

typedef struct {
    uint16_t orig_norm;       // fp16; ‖x‖ before unit-normalization
    uint16_t res_d;           // fp16; ‖residual‖ in original space
    uint8_t  layer_idx;       // packed layer (low 5 bits) + rotation (bit 7)
    uint8_t  qs[24];          // 64 × 3-bit Lloyd-Max indices (bitplane packed)
    uint8_t  qjl_signs[8];   // 64 × 1-bit QJL signs (bit set = negative)
} block_tq4p_d64;

_Static_assert(sizeof(block_tq4p_d64) == 37, "block_tq4p_d64 size");

typedef struct {
    uint16_t orig_norm;
    uint16_t res_d;
    uint8_t  layer_idx;
    uint8_t  qs[48];          // 128 × 3-bit
    uint8_t  qjl_signs[16];  // 128 × 1-bit
} block_tq4p_d128;

_Static_assert(sizeof(block_tq4p_d128) == 69, "block_tq4p_d128 size");

typedef struct {
    uint16_t orig_norm;
    uint16_t res_d;
    uint8_t  layer_idx;
    uint8_t  qs[96];          // 256 × 3-bit
    uint8_t  qjl_signs[32];  // 256 × 1-bit
} block_tq4p_d256;

_Static_assert(sizeof(block_tq4p_d256) == 133, "block_tq4p_d256 size");

#pragma pack(pop)

// ----- BF16 / FP16 types -----
//
// When integrating into ggml, replace with ggml_bf16_t / ggml_fp16_t.
// Both are storage-only uint16_t; we convert to fp32 at load time.
typedef uint16_t ggml_bf16_t;
typedef uint16_t ggml_fp16_t;

// ----- Quantize / dequantize -----

// quantize_row_*: in-place-style conversion of `k` fp32 elements into
// `k / QK_*` packed blocks. `k` must be a multiple of QK_*.
// `layer_byte` packs the per-layer index (low 5 bits), rotation mode
// (bit 7), and the explicit-override flag (bit 6). Use
// TQP_LAYER_BYTE(layer, rotation) to build an explicit byte, or pass
// a packed byte with bit 6 = 0 to let the runtime rotation resolver
// fill rotation from per-thread > per-process env > compile-time WHT.
void ggml_quantize_row_tq4p_d64 (const float * x, block_tq4p_d64  * y, int64_t k, uint8_t layer_byte);
void ggml_quantize_row_tq4p_d128(const float * x, block_tq4p_d128 * y, int64_t k, uint8_t layer_byte);
void ggml_quantize_row_tq4p_d256(const float * x, block_tq4p_d256 * y, int64_t k, uint8_t layer_byte);

// BF16 / FP16 input variants. Convert to fp32 at load; internal pipeline
// (Lloyd-Max, rotations, QJL) stays fp32. The `layer_byte` parameter has
// identical semantics to the fp32 entry points above.
void ggml_quantize_row_tq4p_d64_bf16 (const ggml_bf16_t * x, block_tq4p_d64  * y, int64_t k, uint8_t layer_byte);
void ggml_quantize_row_tq4p_d128_bf16(const ggml_bf16_t * x, block_tq4p_d128 * y, int64_t k, uint8_t layer_byte);
void ggml_quantize_row_tq4p_d256_bf16(const ggml_bf16_t * x, block_tq4p_d256 * y, int64_t k, uint8_t layer_byte);
void ggml_quantize_row_tq4p_d64_f16  (const ggml_fp16_t * x, block_tq4p_d64  * y, int64_t k, uint8_t layer_byte);
void ggml_quantize_row_tq4p_d128_f16 (const ggml_fp16_t * x, block_tq4p_d128 * y, int64_t k, uint8_t layer_byte);
void ggml_quantize_row_tq4p_d256_f16 (const ggml_fp16_t * x, block_tq4p_d256 * y, int64_t k, uint8_t layer_byte);

// 3-arg wrappers for ggml_from_float_t / from_float_ref / from_float
// compatibility. These pass bit 6 = 0 so rotation is resolved at
// runtime via the per-thread > per-process > compile-time cascade.
// Layer defaults to 0; the CUDA cpy dispatch uses the full 4-arg variant
// with layer_byte from the cpy op's op_params[0]. In a real attention
// pass, the attention module should set the thread-local rotation (via
// tqp_set_thread_rotation) before these wrappers fire.
//
// Used by both hook 2 (type_traits.from_float_ref) and hook 3
// (type_traits_cpu.from_float).
static inline void ggml_quantize_row_tq4p_d64_default(const float * x, void * y, int64_t k) {
    ggml_quantize_row_tq4p_d64(x, (block_tq4p_d64 *)y, k, 0x00);
}
static inline void ggml_quantize_row_tq4p_d128_default(const float * x, void * y, int64_t k) {
    ggml_quantize_row_tq4p_d128(x, (block_tq4p_d128 *)y, k, 0x00);
}
static inline void ggml_quantize_row_tq4p_d256_default(const float * x, void * y, int64_t k) {
    ggml_quantize_row_tq4p_d256(x, (block_tq4p_d256 *)y, k, 0x00);
}

// dequantize_row_*: reconstruct fp32 from packed blocks. QJL stage is not
// used for reconstruction (paper: Stage 2 only contributes to inner-product
// estimation). layer_idx is read from each block's header.
void ggml_dequantize_row_tq4p_d64 (const block_tq4p_d64  * x, float * y, int64_t k);
void ggml_dequantize_row_tq4p_d128(const block_tq4p_d128 * x, float * y, int64_t k);
void ggml_dequantize_row_tq4p_d256(const block_tq4p_d256 * x, float * y, int64_t k);

// ----- Inner-product estimator -----
//
// Two-step API, designed so the CUDA follow-up can cache Sq across all K
// positions for a given query:
//
//   ggml_tqp_prepare_query_*(q, Sq): once per query, computes Sq = S · q.
//     q:  d fp32 values, unrotated
//     Sq: d fp32 values, caller-allocated
//
//   ggml_tqp_vec_dot_block_*(q, Sq, blk): per (query, K block) pair.
//     Returns the estimated inner product ⟨q, x⟩.
//
// The CPU reference recomputes Sq for every vec_dot call; callers doing a
// full attention pass should amortize via prepare_query.

// `layer_byte` uses the same packing as ggml_quantize_row_*.
void  ggml_tqp_prepare_query_d64 (const float * q, float * Sq, uint8_t layer_byte);
void  ggml_tqp_prepare_query_d128(const float * q, float * Sq, uint8_t layer_byte);
void  ggml_tqp_prepare_query_d256(const float * q, float * Sq, uint8_t layer_byte);

float ggml_tqp_vec_dot_block_d64 (const float * q, const float * Sq,
                                  const block_tq4p_d64  * blk);
float ggml_tqp_vec_dot_block_d128(const float * q, const float * Sq,
                                  const block_tq4p_d128 * blk);
float ggml_tqp_vec_dot_block_d256(const float * q, const float * Sq,
                                  const block_tq4p_d256 * blk);

// ----- ggml integration glue -----
//
// Thin wrappers matching ggml's vec_dot signature. The fork's dispatch table
// in ggml-cpu/ggml-cpu.c registers these for the new types.
//
// Signature matches ggml_vec_dot_t in ggml-cpu.h:
//   n  = number of elements
//   s  = output scalar (1 float)
//   bs = stride of s in bytes (usually sizeof(float))
//   vx = quantized K-side pointer (tq4p_d* blocks) — first ptr, per ggml convention
//   bx = stride of vx
//   vy = converted query (fp32 for our `vec_dot_type = GGML_TYPE_F32`)
//   by = stride of vy
//   nrc = number of rows to compute (batch; reference impl supports nrc=1)

void ggml_vec_dot_tq4p_d64_f32 (int n, float * s, size_t bs,
                                 const void * vx, size_t bx,
                                 const void * vy, size_t by, int nrc);
void ggml_vec_dot_tq4p_d128_f32(int n, float * s, size_t bs,
                                 const void * vx, size_t bx,
                                 const void * vy, size_t by, int nrc);
void ggml_vec_dot_tq4p_d256_f32(int n, float * s, size_t bs,
                                 const void * vx, size_t bx,
                                 const void * vy, size_t by, int nrc);

// ----- Q8_K-compatible query block -----
//
// Matches the upstream ggml block_q8_K layout (ggml-common.h).
// Used as the query-side type when vec_dot_type = GGML_TYPE_Q8_K.
// The fork's quantize_row_q8_K produces these; we only dequantize here.

#define QK_Q8K 256

#pragma pack(push, 1)
typedef struct {
    float   d;                   // scale (delta)
    int8_t  qs[QK_Q8K];         // quantized values
    int16_t bsums[QK_Q8K / 16]; // sum of quants in groups of 16 (unused here)
} block_q8k_compat;
#pragma pack(pop)

_Static_assert(sizeof(block_q8k_compat) == 292, "block_q8k_compat size");

// ----- Q8_K query dispatch wrappers -----
//
// Same ggml vec_dot signature as the fp32 wrappers above, but vy points to
// block_q8k_compat blocks instead of fp32 values. The implementation
// dequantizes Q8_K to fp32 one block at a time, then applies the same
// Π rotation + QJL estimator. n must be a multiple of 256 (= lcm(D, QK_Q8K)).
//
// Register as the second dispatch entry per type:
//   .vec_dot      = ggml_vec_dot_tq4p_d128_q8k
//   .vec_dot_type = GGML_TYPE_Q8_K

void ggml_vec_dot_tq4p_d64_q8k (int n, float * s, size_t bs,
                                 const void * vx, size_t bx,
                                 const void * vy, size_t by, int nrc);
void ggml_vec_dot_tq4p_d128_q8k(int n, float * s, size_t bs,
                                 const void * vx, size_t bx,
                                 const void * vy, size_t by, int nrc);
void ggml_vec_dot_tq4p_d256_q8k(int n, float * s, size_t bs,
                                 const void * vx, size_t bx,
                                 const void * vy, size_t by, int nrc);

// Maximum number of supported layers for per-layer Π/S matrices.
#define TQP_MAX_LAYERS 32

#ifdef __cplusplus
}
#endif
