// Legacy compatibility aliases for head_dim=64, bits=3.
// Generated by patches/stage2-qjl/python/generate_constants.py

#ifndef TQP_CENTROIDS_D64_H
#define TQP_CENTROIDS_D64_H

#include "tqp_centroids_d64_b3.h"

#define TQP_CENTROIDS_D64 TQP_CENTROIDS_D64_B3
#define TQP_BOUNDARIES_D64 TQP_BOUNDARIES_D64_B3

#endif  // TQP_CENTROIDS_D64_H
