// TQP Lloyd-Max centroids for head_dim=128, bits=2.
// Distortion per coord (Gaussian-approx): 0.000917827
// Generated by patches/stage2-qjl/python/generate_constants.py

#ifndef TQP_CENTROIDS_D128_B2_H
#define TQP_CENTROIDS_D128_B2_H

static const float TQP_CENTROIDS_D128_B2[4] = {
    -1.335033178e-01f, -4.002048075e-02f, +4.002048075e-02f, +1.335033178e-01f,
};

static const float TQP_BOUNDARIES_D128_B2[3] = {
    -8.676189929e-02f, +0.000000000e+00f, +8.676189929e-02f,
};

#endif  // TQP_CENTROIDS_D128_B2_H
