// TQP Lloyd-Max centroids for head_dim=64, bits=2.
// Distortion per coord (Gaussian-approx): 0.001835654
// Generated by patches/stage2-qjl/python/generate_constants.py

#ifndef TQP_CENTROIDS_D64_B2_H
#define TQP_CENTROIDS_D64_B2_H

static const float TQP_CENTROIDS_D64_B2[4] = {
    -1.888021976e-01f, -5.659750476e-02f, +5.659750476e-02f, +1.888021976e-01f,
};

static const float TQP_BOUNDARIES_D64_B2[3] = {
    -1.226998493e-01f, +0.000000000e+00f, +1.226998493e-01f,
};

#endif  // TQP_CENTROIDS_D64_B2_H
