// TQ4P Lloyd-Max centroids for head_dim=128, bits=3.
// Distortion per coord (Gaussian-approx): 0.000269904
// Generated by patches/stage2-qjl/python/generate_constants.py

#ifndef TQP_CENTROIDS_D128_H
#define TQP_CENTROIDS_D128_H

static const float TQP_CENTROIDS_D128[8] = {
    -1.902069300e-01f, -1.187859178e-01f, -6.682205945e-02f, -2.166347019e-02f, +2.166347019e-02f, +6.682205945e-02f, +1.187859178e-01f, +1.902069300e-01f,
};

static const float TQP_BOUNDARIES_D128[7] = {
    -1.544964164e-01f, -9.280399233e-02f, -4.424276203e-02f, -3.469446952e-17f, +4.424276203e-02f, +9.280399233e-02f, +1.544964164e-01f,
};

#endif  // TQP_CENTROIDS_D128_H
