// TQ4P Lloyd-Max centroids for head_dim=64, bits=3.
// Distortion per coord (Gaussian-approx): 0.000539809
// Generated by patches/stage2-qjl/python/generate_constants.py

#ifndef TQP_CENTROIDS_D64_H
#define TQP_CENTROIDS_D64_H

static const float TQP_CENTROIDS_D64[8] = {
    -2.689931989e-01f, -1.679886580e-01f, -9.450066090e-02f, -3.063677251e-02f, +3.063677251e-02f, +9.450066090e-02f, +1.679886580e-01f, +2.689931989e-01f,
};

static const float TQP_BOUNDARIES_D64[7] = {
    -2.184909433e-01f, -1.312446594e-01f, -6.256871670e-02f, +0.000000000e+00f, +6.256871670e-02f, +1.312446594e-01f, +2.184909433e-01f,
};

#endif  // TQP_CENTROIDS_D64_H
