// TQP Lloyd-Max centroids for head_dim=256, bits=2.
// Distortion per coord (Gaussian-approx): 0.000458913
// Generated by patches/stage2-qjl/python/generate_constants.py

#ifndef TQP_CENTROIDS_D256_B2_H
#define TQP_CENTROIDS_D256_B2_H

static const float TQP_CENTROIDS_D256_B2[4] = {
    -9.440109879e-02f, -2.829875238e-02f, +2.829875238e-02f, +9.440109879e-02f,
};

static const float TQP_BOUNDARIES_D256_B2[3] = {
    -6.134992465e-02f, +0.000000000e+00f, +6.134992465e-02f,
};

#endif  // TQP_CENTROIDS_D256_B2_H
