// Legacy compatibility aliases for head_dim=128, bits=3.
// Generated by patches/stage2-qjl/python/generate_constants.py

#ifndef TQP_CENTROIDS_D128_H
#define TQP_CENTROIDS_D128_H

#include "tqp_centroids_d128_b3.h"

#define TQP_CENTROIDS_D128 TQP_CENTROIDS_D128_B3
#define TQP_BOUNDARIES_D128 TQP_BOUNDARIES_D128_B3

#endif  // TQP_CENTROIDS_D128_H
