// TQP Lloyd-Max centroids for head_dim=64, bits=4.
// Distortion per coord (Gaussian-approx): 0.000148453
// Generated by patches/stage2-qjl/python/generate_constants.py

#ifndef TQP_CENTROIDS_D64_B4_H
#define TQP_CENTROIDS_D64_B4_H

static const float TQP_CENTROIDS_D64_B4[16] = {
    -3.416347504e-01f, -2.586961389e-01f, -2.023261786e-01f, -1.570952237e-01f, -1.178499311e-01f, -8.213914186e-02f, -4.853394628e-02f, -1.605891436e-02f,
    +1.605891436e-02f, +4.853394628e-02f, +8.213914186e-02f, +1.178499311e-01f, +1.570952237e-01f, +2.023261786e-01f, +2.586961389e-01f, +3.416347504e-01f,
};

static const float TQP_BOUNDARIES_D64_B4[15] = {
    -3.001654446e-01f, -2.305111587e-01f, -1.797107011e-01f, -1.374725848e-01f, -9.999454021e-02f, -6.533654779e-02f, -3.229643032e-02f, +0.000000000e+00f,
    +3.229643032e-02f, +6.533654779e-02f, +9.999454021e-02f, +1.374725848e-01f, +1.797107011e-01f, +2.305111587e-01f, +3.001654446e-01f,
};

#endif  // TQP_CENTROIDS_D64_B4_H
