// Legacy compatibility aliases for head_dim=256, bits=3.
// Generated by patches/stage2-qjl/python/generate_constants.py

#ifndef TQP_CENTROIDS_D256_H
#define TQP_CENTROIDS_D256_H

#include "tqp_centroids_d256_b3.h"

#define TQP_CENTROIDS_D256 TQP_CENTROIDS_D256_B3
#define TQP_BOUNDARIES_D256 TQP_BOUNDARIES_D256_B3

#endif  // TQP_CENTROIDS_D256_H
