// TQ4P Lloyd-Max centroids for head_dim=256, bits=3.
// Distortion per coord (Gaussian-approx): 0.000134952
// Generated by patches/stage2-qjl/python/generate_constants.py

#ifndef TQP_CENTROIDS_D256_H
#define TQP_CENTROIDS_D256_H

static const float TQP_CENTROIDS_D256[8] = {
    -1.344966143e-01f, -8.399432898e-02f, -4.725033045e-02f, -1.531838626e-02f, +1.531838626e-02f, +4.725033045e-02f, +8.399432898e-02f, +1.344966143e-01f,
};

static const float TQP_BOUNDARIES_D256[7] = {
    -1.092454717e-01f, -6.562232971e-02f, -3.128435835e-02f, +0.000000000e+00f, +3.128435835e-02f, +6.562232971e-02f, +1.092454717e-01f,
};

#endif  // TQP_CENTROIDS_D256_H
