"""
Generate TurboQuant paper-faithful constants for the llama.cpp C port.

For each supported head_dim d, emits:
    tqp_centroids_d{d}.h      — 8 Lloyd-Max centroids + 7 boundaries (fp32)
    tqp_constants_d{d}.h      — Per-layer Π and S matrices (32 layers × d×d)

Also writes a torch state dict (tqp_constants.pt) used by the Python reference
and byte-exact equality tests so they use the *same* bits as the C headers.

Seeds match turboquant.py convention, per-layer:
    Π_i: seed = 42 + i   (layer index i in [0, 31])
    S_i: seed = 43 + i   (which is Π_seed + 1, matching TurboQuantProd)
    centroids: deterministic Lloyd-Max solver (no seed needed, shared across layers)

Run:
    python3 generate_constants.py --out-c ../c --out-pt ../c

Idempotent. Re-run after any change of seed or head_dim support.
"""

from __future__ import annotations

import argparse
import pathlib

import torch

# Make turboquant.py / lloyd_max.py importable from the repo root.
_REPO_ROOT = pathlib.Path(__file__).resolve().parents[3]
import sys
sys.path.insert(0, str(_REPO_ROOT))

from lloyd_max import LloydMaxCodebook
from turboquant import generate_qjl_matrix, generate_rotation_matrix


SUPPORTED_DIMS = (128, 256)
BITS = 3                # Stage 1 Lloyd-Max bits for TQ4P_0
MAX_LAYERS = 32
ROT_SEED_BASE = 42      # Π_i seed = ROT_SEED_BASE + i
QJL_SEED_BASE = 43      # S_i seed = QJL_SEED_BASE + i


def emit_float_array(name: str, values: torch.Tensor) -> str:
    """Emit a float array as a C static const initializer. Row-major."""
    flat = values.flatten().tolist()
    n = len(flat)
    lines = [f"static const float {name}[{n}] = {{"]
    for i in range(0, n, 8):
        chunk = flat[i : i + 8]
        lines.append("    " + ", ".join(f"{v:+.9e}f" for v in chunk) + ",")
    lines.append("};")
    return "\n".join(lines)


def emit_float_3d_array(name: str, layers: list[torch.Tensor], d: int) -> str:
    """Emit a 3D float array [MAX_LAYERS][d*d] as a C static const initializer."""
    n_layers = len(layers)
    inner_size = d * d
    lines = [f"static const float {name}[{n_layers}][{inner_size}] = {{"]
    for li, mat in enumerate(layers):
        flat = mat.flatten().tolist()
        assert len(flat) == inner_size
        lines.append(f"    // layer {li} (seed={ROT_SEED_BASE + li if 'PI' in name else QJL_SEED_BASE + li})")
        lines.append("    {")
        for i in range(0, inner_size, 8):
            chunk = flat[i : i + 8]
            lines.append("        " + ", ".join(f"{v:+.9e}f" for v in chunk) + ",")
        lines.append("    },")
    lines.append("};")
    return "\n".join(lines)


def write_centroids_header(d: int, out_c: pathlib.Path) -> LloydMaxCodebook:
    """Lloyd-Max 3-bit centroids/boundaries for the post-rotation distribution at dim d."""
    cb = LloydMaxCodebook(d, BITS, use_exact=False)  # Gaussian approx, d >= 64
    path = out_c / f"tqp_centroids_d{d}.h"
    content = [
        f"// TQ4P Lloyd-Max centroids for head_dim={d}, bits={BITS}.",
        f"// Distortion per coord (Gaussian-approx): {cb.distortion:.9f}",
        f"// Generated by patches/stage2-qjl/python/generate_constants.py",
        "",
        f"#ifndef TQP_CENTROIDS_D{d}_H",
        f"#define TQP_CENTROIDS_D{d}_H",
        "",
        emit_float_array(f"TQP_CENTROIDS_D{d}", cb.centroids),
        "",
        emit_float_array(f"TQP_BOUNDARIES_D{d}", cb.boundaries),
        "",
        f"#endif  // TQP_CENTROIDS_D{d}_H",
        "",
    ]
    path.write_text("\n".join(content))
    return cb


def write_constants_header(
    d: int,
    pi_layers: list[torch.Tensor],
    s_layers: list[torch.Tensor],
    out_c: pathlib.Path,
) -> None:
    """Per-layer Π and S matrices for head_dim=d, stored fp32 row-major.

    Output: tqp_constants_d{d}.h with 3D arrays [MAX_LAYERS][d*d].
    """
    assert len(pi_layers) == MAX_LAYERS
    assert len(s_layers) == MAX_LAYERS
    for mat in pi_layers + s_layers:
        assert mat.shape == (d, d)

    path = out_c / f"tqp_constants_d{d}.h"
    content = [
        f"// TQ4P per-layer rotation Π and QJL matrix S for head_dim={d}.",
        f"// {MAX_LAYERS} layers, Π_i seed={ROT_SEED_BASE}+i, S_i seed={QJL_SEED_BASE}+i.",
        f"// Stored fp32 row-major. Generated by generate_constants.py.",
        "",
        f"#ifndef TQP_CONSTANTS_D{d}_H",
        f"#define TQP_CONSTANTS_D{d}_H",
        "",
        f"#define TQP_MAX_LAYERS {MAX_LAYERS}",
        "",
        f"// Π[layer][d*d]: row-major. Rotated x = Π_layer · x_unit.",
        emit_float_3d_array(f"TQP_PI_D{d}", pi_layers, d),
        "",
        f"// S[layer][d*d]: row-major. QJL projection p = S_layer · residual.",
        emit_float_3d_array(f"TQP_S_D{d}", s_layers, d),
        "",
        f"#endif  // TQP_CONSTANTS_D{d}_H",
        "",
    ]
    path.write_text("\n".join(content))


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--out-c", type=pathlib.Path,
                        default=pathlib.Path(__file__).parent.parent / "c")
    parser.add_argument("--out-pt", type=pathlib.Path,
                        default=pathlib.Path(__file__).parent.parent / "c")
    args = parser.parse_args()
    args.out_c.mkdir(parents=True, exist_ok=True)
    args.out_pt.mkdir(parents=True, exist_ok=True)

    state: dict[str, torch.Tensor] = {}

    for d in SUPPORTED_DIMS:
        print(f"[+] d={d}: Lloyd-Max centroids")
        cb = write_centroids_header(d, args.out_c)
        state[f"centroids_d{d}"] = cb.centroids
        state[f"boundaries_d{d}"] = cb.boundaries

        pi_layers: list[torch.Tensor] = []
        s_layers: list[torch.Tensor] = []

        for layer_idx in range(MAX_LAYERS):
            rot_seed = ROT_SEED_BASE + layer_idx
            qjl_seed = QJL_SEED_BASE + layer_idx
            pi = generate_rotation_matrix(d, seed=rot_seed)
            s = generate_qjl_matrix(d, m=d, seed=qjl_seed)
            pi_layers.append(pi)
            s_layers.append(s)

        print(f"[+] d={d}: {MAX_LAYERS} per-layer Π (seeds {ROT_SEED_BASE}..{ROT_SEED_BASE + MAX_LAYERS - 1}), "
              f"S (seeds {QJL_SEED_BASE}..{QJL_SEED_BASE + MAX_LAYERS - 1})")

        write_constants_header(d, pi_layers, s_layers, args.out_c)

        # Stack into (MAX_LAYERS, d, d) tensors for the .pt file
        state[f"pi_d{d}"] = torch.stack(pi_layers)
        state[f"s_d{d}"] = torch.stack(s_layers)

    pt_path = args.out_pt / "tqp_constants.pt"
    torch.save(state, pt_path)
    total_kb = sum(t.numel() for t in state.values()) * 4 / 1024
    print(f"[+] wrote {pt_path} ({total_kb:.1f} KB of fp32 state)")


if __name__ == "__main__":
    main()
