"""
Generate TurboQuant paper-faithful constants for the llama.cpp C port.

For each supported head_dim d, emits:
    tqp_centroids_d{d}.h      — 8 Lloyd-Max centroids + 7 boundaries (fp32)
    tqp_constants_d{d}.h      — Π (d×d Haar orthogonal) + S (d×d Gaussian JL)

Also writes a torch state dict (tqp_constants.pt) used by the Python reference
and byte-exact equality tests so they use the *same* bits as the C headers.

Seeds match turboquant.py convention:
    Π: seed = 42
    S: seed = 43 (which is seed + 1 in TurboQuantProd)
    centroids: deterministic Lloyd-Max solver (no seed needed)

Run:
    python3 generate_constants.py --out-c ../c --out-pt ../c

Idempotent. Re-run after any change of seed or head_dim support.
"""

from __future__ import annotations

import argparse
import pathlib

import torch

# Make turboquant.py / lloyd_max.py importable from the repo root.
_REPO_ROOT = pathlib.Path(__file__).resolve().parents[3]
import sys
sys.path.insert(0, str(_REPO_ROOT))

from lloyd_max import LloydMaxCodebook
from turboquant import generate_qjl_matrix, generate_rotation_matrix


SUPPORTED_DIMS = (128, 256)
BITS = 3                # Stage 1 Lloyd-Max bits for TQ4P_0
ROT_SEED = 42
QJL_SEED = 43


def emit_float_array(name: str, values: torch.Tensor) -> str:
    """Emit a float array as a C static const initializer. Row-major."""
    flat = values.flatten().tolist()
    n = len(flat)
    lines = [f"static const float {name}[{n}] = {{"]
    for i in range(0, n, 8):
        chunk = flat[i : i + 8]
        lines.append("    " + ", ".join(f"{v:+.9e}f" for v in chunk) + ",")
    lines.append("};")
    return "\n".join(lines)


def write_centroids_header(d: int, out_c: pathlib.Path) -> LloydMaxCodebook:
    """Lloyd-Max 3-bit centroids/boundaries for the post-rotation distribution at dim d."""
    cb = LloydMaxCodebook(d, BITS, use_exact=False)  # Gaussian approx, d >= 64
    path = out_c / f"tqp_centroids_d{d}.h"
    content = [
        f"// TQ4P Lloyd-Max centroids for head_dim={d}, bits={BITS}.",
        f"// Distortion per coord (Gaussian-approx): {cb.distortion:.9f}",
        f"// Generated by patches/stage2-qjl/python/generate_constants.py",
        "",
        f"#ifndef TQP_CENTROIDS_D{d}_H",
        f"#define TQP_CENTROIDS_D{d}_H",
        "",
        emit_float_array(f"TQP_CENTROIDS_D{d}", cb.centroids),
        "",
        emit_float_array(f"TQP_BOUNDARIES_D{d}", cb.boundaries),
        "",
        f"#endif  // TQP_CENTROIDS_D{d}_H",
        "",
    ]
    path.write_text("\n".join(content))
    return cb


def write_constants_header(d: int, pi: torch.Tensor, s: torch.Tensor, out_c: pathlib.Path) -> None:
    """Π (Haar) and S (Gaussian) matrices for head_dim=d, stored fp32 row-major."""
    assert pi.shape == (d, d)
    assert s.shape == (d, d)
    path = out_c / f"tqp_constants_d{d}.h"
    content = [
        f"// TQ4P rotation Π (Haar, seed={ROT_SEED}) and QJL matrix S (Gaussian, seed={QJL_SEED})",
        f"// for head_dim={d}. Stored fp32 row-major.",
        f"// Generated by patches/stage2-qjl/python/generate_constants.py",
        "",
        f"#ifndef TQP_CONSTANTS_D{d}_H",
        f"#define TQP_CONSTANTS_D{d}_H",
        "",
        f"// Π: d×d row-major. Rotated x = Π · x_unit.",
        emit_float_array(f"TQP_PI_D{d}", pi),
        "",
        f"// S: d×d row-major. QJL projection p = S · r_rot.",
        emit_float_array(f"TQP_S_D{d}", s),
        "",
        f"#endif  // TQP_CONSTANTS_D{d}_H",
        "",
    ]
    path.write_text("\n".join(content))


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--out-c", type=pathlib.Path,
                        default=pathlib.Path(__file__).parent.parent / "c")
    parser.add_argument("--out-pt", type=pathlib.Path,
                        default=pathlib.Path(__file__).parent.parent / "c")
    args = parser.parse_args()
    args.out_c.mkdir(parents=True, exist_ok=True)
    args.out_pt.mkdir(parents=True, exist_ok=True)

    state: dict[str, torch.Tensor] = {}

    for d in SUPPORTED_DIMS:
        print(f"[+] d={d}: Lloyd-Max centroids")
        cb = write_centroids_header(d, args.out_c)
        state[f"centroids_d{d}"] = cb.centroids
        state[f"boundaries_d{d}"] = cb.boundaries

        print(f"[+] d={d}: Haar Π (seed={ROT_SEED}), Gaussian S (seed={QJL_SEED})")
        pi = generate_rotation_matrix(d, seed=ROT_SEED)
        s = generate_qjl_matrix(d, m=d, seed=QJL_SEED)

        write_constants_header(d, pi, s, args.out_c)
        state[f"pi_d{d}"] = pi
        state[f"s_d{d}"] = s

    pt_path = args.out_pt / "tqp_constants.pt"
    torch.save(state, pt_path)
    print(f"[+] wrote {pt_path} ({sum(t.numel() for t in state.values())*4/1024:.1f} KB of fp32 state)")


if __name__ == "__main__":
    main()
