"""
Generate TurboQuant(-ish) constants for the llama.cpp C port.

For each supported head_dim d and Stage-1 Lloyd-Max bit-width b, emits:
    tqp_centroids_d{d}_b{b}.h  — 2^b centroids + (2^b - 1) boundaries (fp32)
    tqp_constants_d{d}.h       — Per-layer sign vector σ (32 × d) for the
                                 RHT rotation, Π matrix (32 × d × d) for
                                 the Haar rotation, and Gaussian QJL
                                 matrix S (32 × d × d).

Also writes a torch state dict (tqp_constants.pt) used by the Python reference
and byte-exact equality tests so they use the *same* bits as the C headers.

Both rotations are emitted because the runtime picks per-block: a bit in
each block's `layer_idx` header byte selects TQP_ROT_WHT vs TQP_ROT_HAAR.
Users who only ever use one rotation still pay the generation / storage
cost for both, but it's small (a few MB per head_dim in the .h files).

Seeds, per-layer (matching turboquant.py::TurboQuantProd(seed=42+i)):
    σ_i: seed = 42 + i          (Rademacher sign vector for WHT)
    Π_i: seed = 42 + i          (Haar orthogonal rotation)
    S_i: seed = 43 + i          (Gaussian QJL matrix)
    centroids: deterministic Lloyd-Max solver (shared across layers).

Run:
    python3 generate_constants.py --bits 2,3,4 --out-c ../c --out-pt ../c

Idempotent. Re-run after any change of seed, head_dim support, or bit-widths.
"""

from __future__ import annotations

import argparse
import pathlib

import torch

# Make turboquant.py / lloyd_max.py importable from the repo root.
_REPO_ROOT = pathlib.Path(__file__).resolve().parents[3]
import sys
sys.path.insert(0, str(_REPO_ROOT))

from lloyd_max import LloydMaxCodebook
from turboquant import generate_qjl_matrix, generate_rotation_matrix


DEFAULT_DIMS = (128, 256)
DEFAULT_BITS = (2, 3, 4)
LEGACY_ALIAS_BITS = 3
MAX_LAYERS = 32
ROT_SEED_BASE = 42      # σ_i seed = ROT_SEED_BASE + i
QJL_SEED_BASE = 43      # S_i seed = QJL_SEED_BASE + i


def generate_sign_vector(d: int, seed: int) -> torch.Tensor:
    """Per-layer Rademacher sign vector σ ∈ {±1}^d for the Randomized
    Hadamard Transform: Π = (1/√d) · H · diag(σ)."""
    gen = torch.Generator(device="cpu")
    gen.manual_seed(seed)
    bits = torch.randint(0, 2, (d,), generator=gen)
    return (2.0 * bits.to(torch.float32) - 1.0)


def emit_float_array(name: str, values: torch.Tensor) -> str:
    """Emit a float array as a C static const initializer. Row-major."""
    flat = values.flatten().tolist()
    n = len(flat)
    lines = [f"static const float {name}[{n}] = {{"]
    for i in range(0, n, 8):
        chunk = flat[i : i + 8]
        lines.append("    " + ", ".join(f"{v:+.9e}f" for v in chunk) + ",")
    lines.append("};")
    return "\n".join(lines)


def emit_float_3d_array(name: str, layers: list[torch.Tensor], d: int, seed_base: int) -> str:
    """Emit a 3D float array [MAX_LAYERS][d*d] as a C static const initializer."""
    n_layers = len(layers)
    inner_size = d * d
    lines = [f"static const float {name}[{n_layers}][{inner_size}] = {{"]
    for li, mat in enumerate(layers):
        flat = mat.flatten().tolist()
        assert len(flat) == inner_size
        lines.append(f"    // layer {li} (seed={seed_base + li})")
        lines.append("    {")
        for i in range(0, inner_size, 8):
            chunk = flat[i : i + 8]
            lines.append("        " + ", ".join(f"{v:+.9e}f" for v in chunk) + ",")
        lines.append("    },")
    lines.append("};")
    return "\n".join(lines)


def emit_sign_2d_array(name: str, layers: list[torch.Tensor], d: int, seed_base: int) -> str:
    """Emit a 2D ±1 float array [MAX_LAYERS][d] as a C static const initializer."""
    n_layers = len(layers)
    lines = [f"static const float {name}[{n_layers}][{d}] = {{"]
    for li, sig in enumerate(layers):
        flat = sig.flatten().tolist()
        assert len(flat) == d
        lines.append(f"    // layer {li} (seed={seed_base + li})")
        lines.append("    {")
        for i in range(0, d, 16):
            chunk = flat[i : i + 16]
            lines.append("        " + ", ".join(f"{int(v):+d}.0f" for v in chunk) + ",")
        lines.append("    },")
    lines.append("};")
    return "\n".join(lines)


def write_centroids_header(d: int, bits: int, out_c: pathlib.Path) -> LloydMaxCodebook:
    """Lloyd-Max centroids/boundaries for the post-rotation distribution."""
    cb = LloydMaxCodebook(d, bits, use_exact=False)  # Gaussian approx, d >= 64
    header_name = f"tqp_centroids_d{d}_b{bits}.h"
    path = out_c / header_name
    centroids_name = f"TQP_CENTROIDS_D{d}_B{bits}"
    boundaries_name = f"TQP_BOUNDARIES_D{d}_B{bits}"
    guard = f"TQP_CENTROIDS_D{d}_B{bits}_H"
    content = [
        f"// TQP Lloyd-Max centroids for head_dim={d}, bits={bits}.",
        f"// Distortion per coord (Gaussian-approx): {cb.distortion:.9f}",
        f"// Generated by patches/stage2-qjl/python/generate_constants.py",
        "",
        f"#ifndef {guard}",
        f"#define {guard}",
        "",
        emit_float_array(centroids_name, cb.centroids),
        "",
        emit_float_array(boundaries_name, cb.boundaries),
        "",
        f"#endif  // {guard}",
        "",
    ]
    path.write_text("\n".join(content))
    return cb


def write_legacy_centroids_alias_header(d: int, out_c: pathlib.Path) -> None:
    """Preserve the historical B3 header and symbol names as aliases."""
    path = out_c / f"tqp_centroids_d{d}.h"
    include_name = f"tqp_centroids_d{d}_b{LEGACY_ALIAS_BITS}.h"
    guard = f"TQP_CENTROIDS_D{d}_H"
    content = [
        f"// Legacy compatibility aliases for head_dim={d}, bits={LEGACY_ALIAS_BITS}.",
        f"// Generated by patches/stage2-qjl/python/generate_constants.py",
        "",
        f"#ifndef {guard}",
        f"#define {guard}",
        "",
        f'#include "{include_name}"',
        "",
        f"#define TQP_CENTROIDS_D{d} TQP_CENTROIDS_D{d}_B{LEGACY_ALIAS_BITS}",
        f"#define TQP_BOUNDARIES_D{d} TQP_BOUNDARIES_D{d}_B{LEGACY_ALIAS_BITS}",
        "",
        f"#endif  // {guard}",
        "",
    ]
    path.write_text("\n".join(content))


def write_constants_header(
    d: int,
    sigma_layers: list[torch.Tensor],
    pi_layers: list[torch.Tensor],
    s_layers: list[torch.Tensor],
    out_c: pathlib.Path,
) -> None:
    """Per-layer σ (RHT), Π (Haar) and S (QJL) for head_dim=d."""
    assert len(sigma_layers) == MAX_LAYERS
    assert len(pi_layers) == MAX_LAYERS
    assert len(s_layers) == MAX_LAYERS
    for sig in sigma_layers:
        assert sig.shape == (d,)
    for mat in pi_layers:
        assert mat.shape == (d, d)
    for mat in s_layers:
        assert mat.shape == (d, d)

    path = out_c / f"tqp_constants_d{d}.h"
    content = [
        f"// TQP per-layer σ (WHT), Π (Haar) and S (QJL) for head_dim={d}.",
        f"// {MAX_LAYERS} layers, σ_i and Π_i seed={ROT_SEED_BASE}+i, S_i seed={QJL_SEED_BASE}+i.",
        f"// Rotation used by a given block is selected by the high bit of",
        f"// the block's layer_idx byte (TQP_ROT_WHT=0, TQP_ROT_HAAR=1).",
        f"// Stored fp32. Generated by generate_constants.py.",
        "",
        f"#ifndef TQP_CONSTANTS_D{d}_H",
        f"#define TQP_CONSTANTS_D{d}_H",
        "",
        f"#define TQP_MAX_LAYERS {MAX_LAYERS}",
        "",
        f"// σ[layer][d]: ±1 per coord. x_rot = (1/√d) · WHT(diag(σ_layer) · x).",
        emit_sign_2d_array(f"TQP_SIGMA_D{d}", sigma_layers, d, ROT_SEED_BASE),
        "",
        f"// Π[layer][d*d]: row-major. Haar random orthogonal. x_rot = Π_layer · x.",
        emit_float_3d_array(f"TQP_PI_D{d}", pi_layers, d, ROT_SEED_BASE),
        "",
        f"// S[layer][d*d]: row-major. QJL projection p = S_layer · residual.",
        emit_float_3d_array(f"TQP_S_D{d}", s_layers, d, QJL_SEED_BASE),
        "",
        f"#endif  // TQP_CONSTANTS_D{d}_H",
        "",
    ]
    path.write_text("\n".join(content))


def parse_csv_ints(raw: str | None, *, default: tuple[int, ...]) -> tuple[int, ...]:
    if raw is None:
        return default
    values = tuple(int(part.strip()) for part in raw.split(",") if part.strip())
    if not values:
        raise ValueError("expected at least one comma-separated integer")
    return values


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument(
        "--out-c",
        type=pathlib.Path,
        default=pathlib.Path(__file__).parent.parent / "c",
    )
    parser.add_argument(
        "--out-pt",
        type=pathlib.Path,
        default=pathlib.Path(__file__).parent.parent / "c",
    )
    parser.add_argument(
        "--dims",
        type=str,
        default=None,
        help="Comma-separated head dims to generate, e.g. '64,128,256'. "
             "Default: 128,256",
    )
    parser.add_argument(
        "--bits",
        type=str,
        default=None,
        help="Comma-separated Stage-1 Lloyd-Max bit-widths to generate, "
             "e.g. '2,3,4'. Default: 2,3,4",
    )
    args = parser.parse_args()
    args.out_c.mkdir(parents=True, exist_ok=True)
    args.out_pt.mkdir(parents=True, exist_ok=True)

    dims = parse_csv_ints(args.dims, default=DEFAULT_DIMS)
    bits_list = parse_csv_ints(args.bits, default=DEFAULT_BITS)

    invalid_bits = tuple(bits for bits in bits_list if bits <= 0)
    if invalid_bits:
        raise ValueError(f"bit-widths must be positive, got {invalid_bits}")

    state: dict[str, torch.Tensor] = {}

    for d in dims:
        for bits in bits_list:
            print(f"[+] d={d}, bits={bits}: Lloyd-Max centroids")
            cb = write_centroids_header(d, bits, args.out_c)
            state[f"centroids_d{d}_b{bits}"] = cb.centroids
            state[f"boundaries_d{d}_b{bits}"] = cb.boundaries
            if bits == LEGACY_ALIAS_BITS:
                state[f"centroids_d{d}"] = cb.centroids
                state[f"boundaries_d{d}"] = cb.boundaries

        if LEGACY_ALIAS_BITS in bits_list:
            write_legacy_centroids_alias_header(d, args.out_c)

        sigma_layers: list[torch.Tensor] = []
        pi_layers: list[torch.Tensor] = []
        s_layers: list[torch.Tensor] = []

        for layer_idx in range(MAX_LAYERS):
            rot_seed = ROT_SEED_BASE + layer_idx
            qjl_seed = QJL_SEED_BASE + layer_idx
            sigma = generate_sign_vector(d, seed=rot_seed)
            pi = generate_rotation_matrix(d, seed=rot_seed)
            s = generate_qjl_matrix(d, m=d, seed=qjl_seed)
            sigma_layers.append(sigma)
            pi_layers.append(pi)
            s_layers.append(s)

        print(
            f"[+] d={d}: {MAX_LAYERS} per-layer σ + Π (seeds {ROT_SEED_BASE}..{ROT_SEED_BASE + MAX_LAYERS - 1}), "
            f"S (seeds {QJL_SEED_BASE}..{QJL_SEED_BASE + MAX_LAYERS - 1})"
        )

        write_constants_header(d, sigma_layers, pi_layers, s_layers, args.out_c)

        # Stack into (MAX_LAYERS, d) / (MAX_LAYERS, d, d) for the .pt file
        state[f"sigma_d{d}"] = torch.stack(sigma_layers)
        state[f"pi_d{d}"] = torch.stack(pi_layers)
        state[f"s_d{d}"] = torch.stack(s_layers)

    pt_path = args.out_pt / "tqp_constants.pt"
    torch.save(state, pt_path)
    total_kb = sum(t.numel() for t in state.values()) * 4 / 1024
    print(f"[+] wrote {pt_path} ({total_kb:.1f} KB of fp32 state)")


if __name__ == "__main__":
    main()
